language: java
dist: trusty
sudo: false # faster builds

# safelist
branches:
  only:
  - master
  - dev

env:
  global:
    - DEV_BRANCH=dev
    - RELEASE_BRANCH=master
    - REPO=ebx/ebx-unixtime-sdk
    - NO_COLOUR='\033[0m'
    - RED_COLOUR='\033[0;31m'
    - GREEN_COLOUR='\033[0;32m'

before_script:
  - export SOURCE_BRANCH_NAME=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi) 
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import || echo "Failed to import GPG_SECRET_KEYS (probably because this branch is a PR)."
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust || echo "Failed to import GPG_OWNERTRUST (probably because this branch is a PR)."
  - source Infrastructure/Build-Scripts/export_mvn_version.sh
  - source Infrastructure/Build-Scripts/validate_build.sh

script:
  - source Infrastructure/Build-Scripts/build_sdk_travis.sh
  
after_failure:
  - cat target/surefire-reports/*.txt

## Prepare the release for Github
## Ensure we have a suitable git tag for the release based on the verison number
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "MarcFletcher"
  - git config --local user.email "marc@echobox.com"
  - export DEPLOY_TAG=v$MVN_VERSION
  - git tag $DEPLOY_TAG
  
## Create the release in Github
deploy:
  provider: releases
  api_key:
    secure: UhX6uT4ak5DyWK9oHE2oUpLMa39U0XTe9J0xcyQ1Wu/uhr+nf5yNMUTIkBybuxL89tB314YJ9XGkXpbQR5ef3xIGyXAtVdaHGqWdRbfoq6JS1/Vep6yxraPgy32G5mA8QFCGzUXqPtDgvZ+VDnJlWflEUm46VPOS8tsHhKxKgstajKcG1iGet4PSeP10TRKQ+G5ubs5UkaHn83+NGxwISx9Ma/cvdiMOp+7otDj1nShYgUTS9KYMP/82JNlgJT2VxbR6XbnoJdnypWWQmoycCUDOOOyhDUB6IXrFt7h1PrWbUTzMl57qZJNDtfsfZFH/Ym7imFcZPaxLuckMBHAJN+V5mPKFM5dXyQfM2z8wfq1/rBhKxkYoX7vDSGUhTU2eE+Cqz5nEx4kYaMa1dMPiYzg+O3m1SnlpZCZOSvDR1SnJVvmR+9VsMKSMRB3cFWD371aaHJux+NgPD1Px8MDJ8/TmKboE+yaVXmvHyDG9pEhLjV8XDvhFjKQLQsA/UUyglY+LxWYWSIDZ7OGXeip58gawH+pfIoWNZ42j0KSSaaXHVheZkhe3LvlAMrKKmqn3T1DgdwSoRWnK9pQAqYd9FfxD9vvr3dCKk/P84VS51QW6CNx9hHVPLGIZxhki+dchSgl15zSRuOWsPkQsnQTprogimZoyZQjq0q28mdtIdGs=
  file: 
    - target/ebx-unixtime-sdk-$MVN_VERSION.jar
    - target/ebx-unixtime-sdk-$MVN_VERSION-javadoc.jar
    - target/ebx-unixtime-sdk-$MVN_VERSION-sources.jar
  edge: true
  on:
    repo: $REPO
    branch: $RELEASE_BRANCH
  name: v$MVN_VERSION
  
cache:
  directories:
    - ~/.m2/repository
